/********************************************************************
* dictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledictionary();
extern void G__cpp_setup_inheritancedictionary();
extern void G__cpp_setup_typetabledictionary();
extern void G__cpp_setup_memvardictionary();
extern void G__cpp_setup_globaldictionary();
extern void G__cpp_setup_memfuncdictionary();
extern void G__cpp_setup_funcdictionary();
extern void G__set_cpp_environmentdictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TLorentzVector.h"
#include "../../../L1TriggerDPG/L1Ntuples/interface/L1AnalysisL1ExtraDataFormat.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__dictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__dictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__dictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictionaryLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__dictionaryLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__dictionaryLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TLorentzVector;
extern G__linked_taginfo G__dictionaryLN_L1Analysis;
extern G__linked_taginfo G__dictionaryLN_L1AnalysiscLcLL1AnalysisL1ExtraDataFormat;
extern G__linked_taginfo G__dictionaryLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__dictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictionaryLN_pairlETLorentzVectorcOTLorentzVectorgR;
extern G__linked_taginfo G__dictionaryLN_vectorlEpairlETLorentzVectorcOTLorentzVectorgRcOallocatorlEpairlETLorentzVectorcOTLorentzVectorgRsPgRsPgR;
extern G__linked_taginfo G__dictionaryLN_vectorlEpairlETLorentzVectorcOTLorentzVectorgRcOallocatorlEpairlETLorentzVectorcOTLorentzVectorgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__dictionaryLN_reverse_iteratorlEvectorlEpairlETLorentzVectorcOTLorentzVectorgRcOallocatorlEpairlETLorentzVectorcOTLorentzVectorgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef pair<TLorentzVector,TLorentzVector> G__pairlETLorentzVectorcOTLorentzVectorgR;
typedef vector<pair<TLorentzVector,TLorentzVector>,allocator<pair<TLorentzVector,TLorentzVector> > > G__vectorlEpairlETLorentzVectorcOTLorentzVectorgRcOallocatorlEpairlETLorentzVectorcOTLorentzVectorgRsPgRsPgR;
